packages:
  - "backend"
  - "web"
  - "mobile"
  - "packages/*"
allowBuilds:
  '@parcel/watcher': false
  '@prisma/client': false
  '@prisma/engines': false
  '@swc/core': false
  esbuild: true
  prisma: false
  sharp: false
  unrs-resolver: false
